[package]
name = "toy_rpc"
version = "0.1.0"
authors = ["Minghua Wu <michael.wu1107@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "codec-bincode"]

std = ["serde/std"]

codec-bincode = []
codec-json = []


[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
features = "0.10.0"
serde_json = "1.0.57"
erased-serde = "0.3.12"
futures = "0.3.5"
async-std = { version = "1.6", features = ["unstable", "attributes"] }
async-trait = "0.1.41"
bincode = "1.3.1"
pin-project = "0.4.23"
log = "0.4.11"
env_logger = "0.7.1"
tide = { version = "0.13.0", optional = true }
lazy_static = "1.4.0"

# local imports
toy_rpc_macros = { path="macros", version = "0.1.0" }

[workspace]
members = [
    "macros",
    "examples/server_client"
]