[package]
name = "toy-rpc"
version = "0.1.1"
authors = ["Minghua Wu <michael.wu1107@gmail.com>"]
edition = "2018"
description = "An async-std based RPC library that mimics the API of golang net/rpc"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/toy-rpc/0.1.0/toy_rpc/"
homepage = "https://github.com/minghuaw/toy-rpc"
repository = "https://github.com/minghuaw/toy-rpc"
keywords = ["async", "rpc", "go", "golang", "async-std"]
categories = ["network-programming", "asynchronous"]
readme = "Readme.md"
exclude = [
    "examples/*",
    ".gitignore",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
    "std", 
    "bincode", 
    "tide",
    "surf",
]

std = ["serde/std"]
logging = []

[dependencies]
# local imports
# toy-rpc-macros = { path="macros", version = "0.1.0" }
toy-rpc-macros = "0.1.0"

# feature gated optional dependecies
bincode = { version = "1.3.1", optional = true }
serde_json = { version = "1.0.59", optional = true }
tide = { version = "0.15.0", optional = true }
surf = { version = "2.1.0", optional = true }

serde = { version = "1.0.117", features = ["derive"] }
features = "0.10.0"
erased-serde = "0.3.12"
futures = "0.3.8"
async-std = { version = "1.7.0", features = ["unstable", "attributes"] }
async-trait = "0.1.42"
pin-project = "1.0.2"
log = "0.4.11"
env_logger = "0.8.2"
lazy_static = "1.4.0"

[workspace]
members = [
    "macros",
    "examples/server_client",
    "examples/tide_integration"
]
