[package]
name = "toy-rpc"
version = "0.4.2"
authors = ["Minghua Wu <michael.wu1107@gmail.com>"]
edition = "2018"
description = "An async-std based RPC library that mimics the API of golang net/rpc"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/toy-rpc/0.4.0/toy_rpc/"
homepage = "https://github.com/minghuaw/toy-rpc"
repository = "https://github.com/minghuaw/toy-rpc"
keywords = ["async", "rpc", "go", "golang", "async-std"]
categories = ["network-programming", "asynchronous"]
readme = "Readme.md"
exclude = [
    "examples/*",
    "transport/*",
    ".gitignore",
    ".idea/*",
    ".vscode/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]
# rustdoc-args = ["--cfg", "docsrs"]

[features]
default = [
    "std", 
    "serde_bincode",
    "tide",
    "surf",
]

docs = ["default", "actix-web"]

std = ["serde/std"]
logging = []
serde_bincode = []
serde_rmp = ["rmp-serde"]

[dev-dependecies]
actix-web = { version = "3.3.2"}


[dependencies]
# local imports
# toy-rpc-macros = { path="macros", version = "0.1.0" }
toy-rpc-macros = "0.1.0"

# feature gated optional dependecies
serde_json = { version = "1.0.60", optional = true }
serde_cbor = { version = "0.11.1", optional = true }
rmp-serde = { version = "0.14.4", optional = true }
tide = { version = "0.15.0", optional = true }
surf = { version = "2.1.0", optional = true }
actix-web = { version = "3.3.2", optional = true }

bincode = { version = "1.3.1" }
serde = { version = "1.0.117", features = ["derive"] }
erased-serde = "0.3.12"
futures = "0.3.8"
async-std = { version = "1.7.0", features = ["attributes"] }
async-trait = "0.1.42"
pin-project = "1.0.2"
log = "0.4.11"
lazy_static = "1.4.0"

[workspace]
members = [
    "macros",
]

exclude = [
    "examples/server_client",
    "examples/tide_integration",
    "examples/actix_v3_integration"
]
