[package]
name = "toy-rpc"
version = "0.1.0"
authors = ["Minghua Wu <michael.wu1107@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "codec_bincode", "http_tide"]

std = ["serde/std"]

codec_bincode = []
codec_json = []

http_tide = ["tide"]


[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
features = "0.10.0"
serde_json = "1.0.58"
erased-serde = "0.3.12"
futures = "0.3.6"
async-std = { version = "1.6", features = ["unstable", "attributes"] }
async-trait = "0.1.41"
bincode = "1.3.1"
pin-project = "0.4.26"
log = "0.4.11"
env_logger = "0.7.1"
lazy_static = "1.4.0"

# optional dependecies
tide = { version = "0.13.0", optional = true }

# local imports
toy_rpc_macros = { path="macros", version = "0.1.0" }
surf = "2.1.0"

[workspace]
members = [
    "macros",
    "examples/server_client",
    "examples/tide_integration"
]
