[package]
name = "toy-rpc"
version = "0.4.5"
authors = ["Minghua Wu <michael.wu1107@gmail.com>"]
edition = "2018"
description = "An async-std based RPC library that mimics the API of golang net/rpc"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/toy-rpc/0.4.4/toy_rpc/"
homepage = "https://github.com/minghuaw/toy-rpc"
repository = "https://github.com/minghuaw/toy-rpc"
keywords = ["async", "rpc", "go", "golang", "async-std"]
categories = ["network-programming", "asynchronous"]
readme = "Readme.md"
exclude = [
    "examples/*",
    "transport/*",
    ".gitignore",
    ".idea/*",
    ".vscode/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
default = [
    "std", 
    "serde_bincode",
    "tide",
    "surf",
]

docs = ["default", "actix-web"]

std = ["serde/std"]
logging = []
serde_bincode = []
serde_rmp = ["rmp-serde"]

[dev-dependencies]
async-tungstenite = "0.11"
url = "2.2"
tide-websockets = "0.1.0"
tide = {version = "0.15.0", default-features = false, features = ["h1-server"] }

[dependencies]
# local imports
# toy-rpc-macros = { path="macros", version = "0.1.0" }
toy-rpc-macros = "0.1.0"

# feature gated optional dependecies
serde_json = { version = "1.0", optional = true }
serde_cbor = { version = "0.11", optional = true }
rmp-serde = { version = "0.15", optional = true }
tide = { version = "0.15", optional = true }
surf = { version = "2.1.0", optional = true }
actix-web = { version = "3.3", optional = true }

bincode = { version = "1.3" }
serde = { version = "1.0", features = ["derive"] }
erased-serde = "0.3"
futures = "0.3"
async-std = "1.8.0"
async-trait = "0.1"
pin-project = "1.0"
log = "0.4"
lazy_static = "1.4.0"

# websocket dependencies, consider feature gating in the future
tungstenite = "0.11.1"
async-tungstenite = { version = "0.11.0", features = ["async-std-runtime"] }
tide-websockets = "0.1.0"
tokio-tungstenite = "0.12.0"
warp = "0.2.5"

[workspace]
members = [
    "macros",
]

exclude = [
    "examples/server_client",
    "examples/tide_integration",
    "examples/actix_v3_integration"
]
