[package]
name = "actix_v3_integration"
version = "0.1.0"
authors = ["Minghua Wu <michael.wu1107@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
toy-rpc = { version = "0.3.1", path = "../..", default-features = false, features = ["std", "serde_bincode", "actix-web", "surf"]}


[dependencies]
toy-rpc = { version = "0.3.1", path = "../..", default-features = false, features = ["std", "serde_bincode", "actix-web", "surf"]}
actix-web = "3.3.1"
async-std = "1.7.0"

serde = { version = "1.0.117", features = ["derive"] }
async-trait = "0.1.42"
env_logger = "0.8.2"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs" 