[config]
skip_core_tasks = true

[tasks.test]
run_task = [
    { name = ["test_async_std_tcp", "test_tokio_tcp"] },
]

[tasks.test_async_std_tcp]
command = "cargo"
args = ["test", 
    "--features", "serde_bincode async_std_runtime", 
    "--no-default-features", 
    "--test", "async_std_tcp", 
    "--", "--nocapture"
]

[tasks.test_tokio_tcp]
command = "cargo"
args = ["test", 
    "--features", "serde_bincode tokio_runtime", 
    "--no-default-features", 
    "--test", "tokio_tcp", 
    "--", "--nocapture"
]

[tasks.test_async_std_ws]
command = "cargo"
args = ["test",
    "--features", "serde_bincode async_std_runtime",
    "--no-default-features",
    "--test", "async_std_ws",
    "--", "--nocapture"
]

[tasks.doctest]
toolchain = "nightly"
command = "cargo"
args = [
    "doc", "--no-deps", "--all-features", "--open"
]